const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
    user: process.env.DB_USER,
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD,
    port: process.env.DB_PORT,
});

async function removeConstraint() {
    try {
        console.log('Removing CHECK constraint on current_stock...');

        // We need to know the name of the constraint. usually it is components_current_stock_check
        // But to be safe, we can try to drop it by name, and if it fails, maybe we just ALTER COLUMN DROP NOT NULL? No, it's the CHECK.

        // Try standard name
        try {
            await pool.query('ALTER TABLE components DROP CONSTRAINT components_current_stock_check');
            console.log('Constraint components_current_stock_check dropped.');
        } catch (e) {
            console.log('Could not drop by standard name (might not exist or different name):', e.message);

            // If the name is dynamic, we might have to just try to alter the column validation? 
            // Postgres doesn't easily let you "remove check" without name.
            // Let's assume standard default name generated by "CHECK (current_stock >= 0)"
        }

    } catch (err) {
        console.error('Error:', err);
    } finally {
        await pool.end();
    }
}

removeConstraint();
